Update CI tests from Rust v1.41 to v1.70 (plus stable & nightly)
v1.70 is required by the `home` crate:

> error: package `home v0.5.9` cannot be built because it requires rustc 1.70.0 or newer, while the currently active rustc version is 1.63.0

.